//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.DAL.XCCloud
{
    
    using XCCloudWebBar.DAL.Base;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    public partial class Flw_MemberCard_FreeDAL : BaseDAL<Flw_MemberCard_Free>, IFlw_MemberCard_FreeDAL
    {
    		
    }
}
