//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_WechatFunction
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> FunctionType { get; set; }
        public string ViewURL { get; set; }
        public string AppID { get; set; }
        public string StartView { get; set; }
        public string Note { get; set; }
    }
}
