//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_CouponList
    {
        public string ID { get; set; }
        public Nullable<int> CouponIndex { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> CouponID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> PublishType { get; set; }
        public Nullable<int> SendType { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> JackpotID { get; set; }
        public Nullable<int> SendAuthorID { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> WorkStationID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IsLock { get; set; }
        public string Verifiction { get; set; }
    }
}
