//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_MemberLevel
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string MemberLevelName { get; set; }
        public string CoverURL { get; set; }
        public Nullable<decimal> OpenFee { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> ClearPointDays { get; set; }
        public Nullable<int> Validday { get; set; }
        public Nullable<int> NeedAuthor { get; set; }
        public Nullable<int> MustPhone { get; set; }
        public Nullable<int> PhoneOnly { get; set; }
        public Nullable<int> MustIDCard { get; set; }
        public Nullable<int> UseReadID { get; set; }
        public Nullable<int> IDCardOnly { get; set; }
        public Nullable<int> ReadFace { get; set; }
        public Nullable<int> ReadPlam { get; set; }
        public Nullable<decimal> ChangeFee { get; set; }
        public Nullable<decimal> RechargeFee { get; set; }
        public Nullable<decimal> ContinueFee { get; set; }
        public Nullable<int> ContinueUsePoint { get; set; }
        public Nullable<decimal> ConsumeTotle { get; set; }
        public Nullable<int> UpdateUsePoint { get; set; }
        public Nullable<int> UpdateLevelID { get; set; }
        public Nullable<int> NonActiveDays { get; set; }
        public Nullable<int> ReduceLevelID { get; set; }
        public Nullable<int> FreeBalanceIndex { get; set; }
        public Nullable<int> WinBalanceIndex { get; set; }
        public Nullable<int> FreeCoin { get; set; }
        public Nullable<int> FreeType { get; set; }
        public Nullable<int> FreeNeedWin { get; set; }
        public Nullable<int> BirthdayFree { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> MinCoin { get; set; }
        public Nullable<int> MaxCoin { get; set; }
        public Nullable<int> AllowExitCard { get; set; }
        public Nullable<int> AllowExitMoney { get; set; }
        public Nullable<int> AllowExitCoinToCard { get; set; }
        public Nullable<int> LockHead { get; set; }
        public Nullable<int> AllowCharge { get; set; }
        public Nullable<int> AllowSaveLottery { get; set; }
        public Nullable<int> AllowSaveCoin { get; set; }
        public Nullable<int> AllowGetCoin { get; set; }
        public Nullable<int> AllowTransferOut { get; set; }
        public Nullable<int> TransferOutLevelID { get; set; }
        public Nullable<int> AllowTransferIn { get; set; }
        public Nullable<int> TransferInLevelID { get; set; }
        public Nullable<int> State { get; set; }
        public string Verifiction { get; set; }
    }
}
