//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_PushRule
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> Allow_Out { get; set; }
        public Nullable<int> Allow_In { get; set; }
        public Nullable<int> WeekType { get; set; }
        public string Week { get; set; }
        public Nullable<int> PushBalanceIndex1 { get; set; }
        public Nullable<int> PushCoin1 { get; set; }
        public Nullable<int> PushBalanceIndex2 { get; set; }
        public Nullable<int> PushCoin2 { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Verifiction { get; set; }
    }
}
