//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_ProjectTicket_Bind
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public Nullable<int> AllowShareCount { get; set; }
        public Nullable<int> WeightValue { get; set; }
        public string Verifiction { get; set; }
    }
}
