//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_MemberLevelFree_Detail
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string MemberFreeID { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<decimal> GetCount { get; set; }
        public string Verifiction { get; set; }
    }
}
