//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Food_Exit
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string OrderID { get; set; }
        public string FoodID { get; set; }
        public string CardID { get; set; }
        public Nullable<decimal> ExitFee { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxFee { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ScheduleID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public string WorkStation { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Verifiction { get; set; }
    }
}
