//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_GroupVerity
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string TicketCode { get; set; }
        public string GroupID { get; set; }
        public Nullable<int> GroupType { get; set; }
        public Nullable<int> FoodID { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> Coin { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<System.DateTime> VerityTime { get; set; }
        public Nullable<int> VerityType { get; set; }
        public Nullable<int> WorkStationID { get; set; }
        public string ScheduleID { get; set; }
        public string Remark { get; set; }
    }
}
