//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_DiscountRule
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string OrderFlwID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<decimal> FreeMoney { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public string Verifiction { get; set; }
    }
}
