//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.DAL.IDAL.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    using XCCloudService.Model.XCCloud;
    public interface IFlw_Project_BuyDetailDAL : IBaseDAL<Flw_Project_BuyDetail>
    {
    		
    }
}
