//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Data_Project_BandPriceService : BaseService<Data_Project_BandPrice>, IData_Project_BandPriceService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_Project_BandPriceService()
            : this(false)
        {
    
        }
    
        public Data_Project_BandPriceService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_Project_BandPriceDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_Project_BandPriceService I
        {
            get
            {
                return BLLContainer.Resolve<IData_Project_BandPriceService>();
            }
        }
    
        public static IData_Project_BandPriceService N
        {
            get
            {
                return BLLContainer.Resolve<IData_Project_BandPriceService>(resolveNew: true);
            }
        }
    }
}
