//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Data_GoodRequest_ListService : BaseService<Data_GoodRequest_List>, IData_GoodRequest_ListService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_GoodRequest_ListService()
            : this(false)
        {
    
        }
    
        public Data_GoodRequest_ListService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_GoodRequest_ListDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_GoodRequest_ListService I
        {
            get
            {
                return BLLContainer.Resolve<IData_GoodRequest_ListService>();
            }
        }
    
        public static IData_GoodRequest_ListService N
        {
            get
            {
                return BLLContainer.Resolve<IData_GoodRequest_ListService>(resolveNew: true);
            }
        }
    }
}
