//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Data_GoodExit_DetailService : BaseService<Data_GoodExit_Detail>, IData_GoodExit_DetailService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_GoodExit_DetailService()
            : this(false)
        {
    
        }
    
        public Data_GoodExit_DetailService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_GoodExit_DetailDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_GoodExit_DetailService I
        {
            get
            {
                return BLLContainer.Resolve<IData_GoodExit_DetailService>();
            }
        }
    
        public static IData_GoodExit_DetailService N
        {
            get
            {
                return BLLContainer.Resolve<IData_GoodExit_DetailService>(resolveNew: true);
            }
        }
    }
}
