//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Data_RuleOverlying_GroupService : BaseService<Data_RuleOverlying_Group>, IData_RuleOverlying_GroupService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_RuleOverlying_GroupService()
            : this(false)
        {
    
        }
    
        public Data_RuleOverlying_GroupService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_RuleOverlying_GroupDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_RuleOverlying_GroupService I
        {
            get
            {
                return BLLContainer.Resolve<IData_RuleOverlying_GroupService>();
            }
        }
    
        public static IData_RuleOverlying_GroupService N
        {
            get
            {
                return BLLContainer.Resolve<IData_RuleOverlying_GroupService>(resolveNew: true);
            }
        }
    }
}
