//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Divide_ProjectInfoService : BaseService<Divide_ProjectInfo>, IDivide_ProjectInfoService
    {
    	public override void SetDal()
        {
    
        }
    
        public Divide_ProjectInfoService()
            : this(false)
        {
    
        }
    
        public Divide_ProjectInfoService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IDivide_ProjectInfoDAL>(resolveNew: resolveNew);
        }
    
    	public static IDivide_ProjectInfoService I
        {
            get
            {
                return BLLContainer.Resolve<IDivide_ProjectInfoService>();
            }
        }
    
        public static IDivide_ProjectInfoService N
        {
            get
            {
                return BLLContainer.Resolve<IDivide_ProjectInfoService>(resolveNew: true);
            }
        }
    }
}
