//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Flw_ProjectTicket_BindService : BaseService<Flw_ProjectTicket_Bind>, IFlw_ProjectTicket_BindService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_ProjectTicket_BindService()
            : this(false)
        {
    
        }
    
        public Flw_ProjectTicket_BindService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_ProjectTicket_BindDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_ProjectTicket_BindService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_ProjectTicket_BindService>();
            }
        }
    
        public static IFlw_ProjectTicket_BindService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_ProjectTicket_BindService>(resolveNew: true);
            }
        }
    }
}
