//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Flw_GameData_WinPrizeService : BaseService<Flw_GameData_WinPrize>, IFlw_GameData_WinPrizeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_GameData_WinPrizeService()
            : this(false)
        {
    
        }
    
        public Flw_GameData_WinPrizeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_GameData_WinPrizeDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_GameData_WinPrizeService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_GameData_WinPrizeService>();
            }
        }
    
        public static IFlw_GameData_WinPrizeService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_GameData_WinPrizeService>(resolveNew: true);
            }
        }
    }
}
