//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Flw_Project_Play_TimeService : BaseService<Flw_Project_Play_Time>, IFlw_Project_Play_TimeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_Project_Play_TimeService()
            : this(false)
        {
    
        }
    
        public Flw_Project_Play_TimeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_Project_Play_TimeDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_Project_Play_TimeService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Project_Play_TimeService>();
            }
        }
    
        public static IFlw_Project_Play_TimeService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Project_Play_TimeService>(resolveNew: true);
            }
        }
    }
}
