//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Flw_Project_PlayTimeService : BaseService<Flw_Project_PlayTime>, IFlw_Project_PlayTimeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_Project_PlayTimeService()
            : this(false)
        {
    
        }
    
        public Flw_Project_PlayTimeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_Project_PlayTimeDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_Project_PlayTimeService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Project_PlayTimeService>();
            }
        }
    
        public static IFlw_Project_PlayTimeService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Project_PlayTimeService>(resolveNew: true);
            }
        }
    }
}
