//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class Search_Template_DetailService : BaseService<Search_Template_Detail>, ISearch_Template_DetailService
    {
    	public override void SetDal()
        {
    
        }
    
        public Search_Template_DetailService()
            : this(false)
        {
    
        }
    
        public Search_Template_DetailService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<ISearch_Template_DetailDAL>(resolveNew: resolveNew);
        }
    
    	public static ISearch_Template_DetailService I
        {
            get
            {
                return BLLContainer.Resolve<ISearch_Template_DetailService>();
            }
        }
    
        public static ISearch_Template_DetailService N
        {
            get
            {
                return BLLContainer.Resolve<ISearch_Template_DetailService>(resolveNew: true);
            }
        }
    }
}
