//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.BLL.XCCloud
{
    
    using XCCloudService.DAL.Container;
    using XCCloudService.DAL.IDAL.XCCloud;
    using XCCloudService.BLL.Base;
    using XCCloudService.BLL.Container;
    using XCCloudService.BLL.IBLL.XCCloud;
    using XCCloudService.Model.XCCloud;
    
    public partial class XC_HolidayListService : BaseService<XC_HolidayList>, IXC_HolidayListService
    {
    	public override void SetDal()
        {
    
        }
    
        public XC_HolidayListService()
            : this(false)
        {
    
        }
    
        public XC_HolidayListService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IXC_HolidayListDAL>(resolveNew: resolveNew);
        }
    
    	public static IXC_HolidayListService I
        {
            get
            {
                return BLLContainer.Resolve<IXC_HolidayListService>();
            }
        }
    
        public static IXC_HolidayListService N
        {
            get
            {
                return BLLContainer.Resolve<IXC_HolidayListService>(resolveNew: true);
            }
        }
    }
}
