//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_DeviceInfo_Ext
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> Motor1EN { get; set; }
        public Nullable<int> Motor2EN { get; set; }
        public Nullable<int> Motor1Coin { get; set; }
        public Nullable<int> Motor2Coin { get; set; }
        public Nullable<int> MaxSaveCount { get; set; }
        public Nullable<int> FromDevice { get; set; }
        public Nullable<decimal> ToCard { get; set; }
        public Nullable<int> BalanceIndex { get; set; }
        public Nullable<int> SSRLevel { get; set; }
        public Nullable<int> DigitCoinEN { get; set; }
        public Nullable<int> DubleCheck { get; set; }
    }
}
