//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_StoreHKConfig
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string HKShopID { get; set; }
        public string HKStoreSecret { get; set; }
        public string HKOrgID { get; set; }
        public string HKMerchID { get; set; }
        public string HKAppSecret { get; set; }
        public string HKAppID { get; set; }
    }
}
