//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GoodRequest_List
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<int> RequestCount { get; set; }
        public Nullable<int> SendCount { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> LogistType { get; set; }
        public string LogistOrderID { get; set; }
    }
}
