//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_WorkFlow_Node
    {
        public int ID { get; set; }
        public Nullable<int> WorkID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> AuthorFlag { get; set; }
        public Nullable<int> Timeout { get; set; }
    }
}
