//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GoodOutOrder
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> OPUserID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> AuthorTime { get; set; }
        public Nullable<int> CancelUserID { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string WorkStation { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> State { get; set; }
        public string Verifiction { get; set; }
    }
}
