//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Project_TimeInfo
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> ProjectTimeID { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<int> FreeMinute { get; set; }
        public Nullable<decimal> AccompanyCash { get; set; }
        public Nullable<int> BalanceIndex { get; set; }
        public Nullable<decimal> Coins { get; set; }
        public Nullable<int> ChargeBalanceIndex { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> CycleTimes { get; set; }
        public Nullable<decimal> TopPrice { get; set; }
        public Nullable<int> CycleType { get; set; }
        public Nullable<int> LockMember { get; set; }
    }
}
