//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_WorkFlow_Entry
    {
        public string ID { get; set; }
        public string WorkID { get; set; }
        public string EventID { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Note { get; set; }
    }
}
