//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_GameData_WinPrize
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> GameIndex { get; set; }
        public string GameSiteName { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> IntervalTimes { get; set; }
        public Nullable<decimal> IntervalPrice { get; set; }
        public Nullable<int> WatchCount { get; set; }
        public Nullable<int> PrizeType { get; set; }
        public Nullable<int> BalanceIndex { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<decimal> PrizeCount { get; set; }
        public string MemberName { get; set; }
        public string ICCardID { get; set; }
        public string MemberID { get; set; }
        public Nullable<decimal> RemainBalance { get; set; }
        public string CreateStoreID { get; set; }
        public Nullable<System.DateTime> WinTime { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<int> GiveFreeType { get; set; }
        public Nullable<int> GiveFreeRuleID { get; set; }
        public Nullable<decimal> GiveFreeCount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> SyncFlag { get; set; }
        public string Verifiction { get; set; }
    }
}
