//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_MemberData
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string CardIndex { get; set; }
        public string ICCardID { get; set; }
        public string MemberLevelName { get; set; }
        public Nullable<int> ChannelType { get; set; }
        public Nullable<int> OperationType { get; set; }
        public Nullable<System.DateTime> OPTime { get; set; }
        public Nullable<int> SourceType { get; set; }
        public string SourceID { get; set; }
        public Nullable<int> BalanceIndex { get; set; }
        public Nullable<decimal> ChangeValue { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> FreeChangeValue { get; set; }
        public Nullable<decimal> FreeBalance { get; set; }
        public Nullable<decimal> BalanceTotal { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string ScheduleID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string WorkStation { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Verifiction { get; set; }
    }
}
