//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_DeviceData
    {
        public string ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> GameIndexID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> SN { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public string MemberID { get; set; }
        public string CreateStoreID { get; set; }
        public string MemberName { get; set; }
        public string ICCardID { get; set; }
        public Nullable<int> BalanceIndex { get; set; }
        public Nullable<decimal> Coin { get; set; }
        public Nullable<decimal> RemainBalance { get; set; }
        public string OrderID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Verifiction { get; set; }
    }
}
