//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_GameAPP_MemberRule
    {
        public string ID { get; set; }
        public Nullable<int> RuleID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public Nullable<int> PushBalanceIndex1 { get; set; }
        public Nullable<decimal> PushCoin1 { get; set; }
        public Nullable<int> PushBalanceIndex2 { get; set; }
        public Nullable<decimal> PushCoin2 { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public string Verifiction { get; set; }
    }
}
