//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Project_TicketDeviceLog
    {
        public string ID { get; set; }
        public string TicketUseID { get; set; }
        public string ProjectTicketCode { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<int> LogType { get; set; }
    }
}
