//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Project_PlayTime
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<int> RecordChannel { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<int> CycleType { get; set; }
        public Nullable<int> LockMember { get; set; }
        public Nullable<int> FreeMinute { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> CycleTimes { get; set; }
        public Nullable<decimal> TopPrice { get; set; }
        public Nullable<int> OutChargeType { get; set; }
        public Nullable<int> ChargeBalanceIndex { get; set; }
        public Nullable<decimal> ChargeCount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<int> PayType { get; set; }
        public string PayOrderID { get; set; }
        public Nullable<int> PayState { get; set; }
        public string QrCode { get; set; }
    }
}
