//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_CheckDate
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> AuthorTime { get; set; }
        public Nullable<decimal> CashTotle { get; set; }
        public Nullable<decimal> AliPay { get; set; }
        public Nullable<decimal> AliPayFee { get; set; }
        public Nullable<decimal> Wechat { get; set; }
        public Nullable<decimal> WechatFee { get; set; }
        public Nullable<decimal> GroupTotle { get; set; }
        public Nullable<decimal> GroupFee { get; set; }
        public Nullable<int> MemberCount { get; set; }
        public Nullable<int> MemberCardCount { get; set; }
        public Nullable<decimal> DepositTotle { get; set; }
    }
}
