//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Base_Goodinfo_PriceService : BaseService<Base_Goodinfo_Price>, IBase_Goodinfo_PriceService
    {
    	public override void SetDal()
        {
    
        }
    
        public Base_Goodinfo_PriceService()
            : this(false)
        {
    
        }
    
        public Base_Goodinfo_PriceService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IBase_Goodinfo_PriceDAL>(resolveNew: resolveNew);
        }
    
    	public static IBase_Goodinfo_PriceService I
        {
            get
            {
                return BLLContainer.Resolve<IBase_Goodinfo_PriceService>();
            }
        }
    
        public static IBase_Goodinfo_PriceService N
        {
            get
            {
                return BLLContainer.Resolve<IBase_Goodinfo_PriceService>(resolveNew: true);
            }
        }
    }
}
