//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Base_EnumParamsService : BaseService<Base_EnumParams>, IBase_EnumParamsService
    {
    	public override void SetDal()
        {
    
        }
    
        public Base_EnumParamsService()
            : this(false)
        {
    
        }
    
        public Base_EnumParamsService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IBase_EnumParamsDAL>(resolveNew: resolveNew);
        }
    
    	public static IBase_EnumParamsService I
        {
            get
            {
                return BLLContainer.Resolve<IBase_EnumParamsService>();
            }
        }
    
        public static IBase_EnumParamsService N
        {
            get
            {
                return BLLContainer.Resolve<IBase_EnumParamsService>(resolveNew: true);
            }
        }
    }
}
