//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_ProjectTicket_BindService : BaseService<Data_ProjectTicket_Bind>, IData_ProjectTicket_BindService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_ProjectTicket_BindService()
            : this(false)
        {
    
        }
    
        public Data_ProjectTicket_BindService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_ProjectTicket_BindDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_ProjectTicket_BindService I
        {
            get
            {
                return BLLContainer.Resolve<IData_ProjectTicket_BindService>();
            }
        }
    
        public static IData_ProjectTicket_BindService N
        {
            get
            {
                return BLLContainer.Resolve<IData_ProjectTicket_BindService>(resolveNew: true);
            }
        }
    }
}
