//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_ProjectTicketService : BaseService<Data_ProjectTicket>, IData_ProjectTicketService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_ProjectTicketService()
            : this(false)
        {
    
        }
    
        public Data_ProjectTicketService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_ProjectTicketDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_ProjectTicketService I
        {
            get
            {
                return BLLContainer.Resolve<IData_ProjectTicketService>();
            }
        }
    
        public static IData_ProjectTicketService N
        {
            get
            {
                return BLLContainer.Resolve<IData_ProjectTicketService>(resolveNew: true);
            }
        }
    }
}
