//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_GameInfo_PhotoService : BaseService<Data_GameInfo_Photo>, IData_GameInfo_PhotoService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_GameInfo_PhotoService()
            : this(false)
        {
    
        }
    
        public Data_GameInfo_PhotoService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_GameInfo_PhotoDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_GameInfo_PhotoService I
        {
            get
            {
                return BLLContainer.Resolve<IData_GameInfo_PhotoService>();
            }
        }
    
        public static IData_GameInfo_PhotoService N
        {
            get
            {
                return BLLContainer.Resolve<IData_GameInfo_PhotoService>(resolveNew: true);
            }
        }
    }
}
