//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_Food_DetialService : BaseService<Data_Food_Detial>, IData_Food_DetialService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_Food_DetialService()
            : this(false)
        {
    
        }
    
        public Data_Food_DetialService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_Food_DetialDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_Food_DetialService I
        {
            get
            {
                return BLLContainer.Resolve<IData_Food_DetialService>();
            }
        }
    
        public static IData_Food_DetialService N
        {
            get
            {
                return BLLContainer.Resolve<IData_Food_DetialService>(resolveNew: true);
            }
        }
    }
}
