//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_GameFreeRule_ListService : BaseService<Data_GameFreeRule_List>, IData_GameFreeRule_ListService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_GameFreeRule_ListService()
            : this(false)
        {
    
        }
    
        public Data_GameFreeRule_ListService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_GameFreeRule_ListDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_GameFreeRule_ListService I
        {
            get
            {
                return BLLContainer.Resolve<IData_GameFreeRule_ListService>();
            }
        }
    
        public static IData_GameFreeRule_ListService N
        {
            get
            {
                return BLLContainer.Resolve<IData_GameFreeRule_ListService>(resolveNew: true);
            }
        }
    }
}
