//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Data_GameAPP_RuleService : BaseService<Data_GameAPP_Rule>, IData_GameAPP_RuleService
    {
    	public override void SetDal()
        {
    
        }
    
        public Data_GameAPP_RuleService()
            : this(false)
        {
    
        }
    
        public Data_GameAPP_RuleService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IData_GameAPP_RuleDAL>(resolveNew: resolveNew);
        }
    
    	public static IData_GameAPP_RuleService I
        {
            get
            {
                return BLLContainer.Resolve<IData_GameAPP_RuleService>();
            }
        }
    
        public static IData_GameAPP_RuleService N
        {
            get
            {
                return BLLContainer.Resolve<IData_GameAPP_RuleService>(resolveNew: true);
            }
        }
    }
}
