//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Dict_AreaService : BaseService<Dict_Area>, IDict_AreaService
    {
    	public override void SetDal()
        {
    
        }
    
        public Dict_AreaService()
            : this(false)
        {
    
        }
    
        public Dict_AreaService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IDict_AreaDAL>(resolveNew: resolveNew);
        }
    
    	public static IDict_AreaService I
        {
            get
            {
                return BLLContainer.Resolve<IDict_AreaService>();
            }
        }
    
        public static IDict_AreaService N
        {
            get
            {
                return BLLContainer.Resolve<IDict_AreaService>(resolveNew: true);
            }
        }
    }
}
