//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Dict_BalanceTypeService : BaseService<Dict_BalanceType>, IDict_BalanceTypeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Dict_BalanceTypeService()
            : this(false)
        {
    
        }
    
        public Dict_BalanceTypeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IDict_BalanceTypeDAL>(resolveNew: resolveNew);
        }
    
    	public static IDict_BalanceTypeService I
        {
            get
            {
                return BLLContainer.Resolve<IDict_BalanceTypeService>();
            }
        }
    
        public static IDict_BalanceTypeService N
        {
            get
            {
                return BLLContainer.Resolve<IDict_BalanceTypeService>(resolveNew: true);
            }
        }
    }
}
