//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_DeviceDataService : BaseService<Flw_DeviceData>, IFlw_DeviceDataService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_DeviceDataService()
            : this(false)
        {
    
        }
    
        public Flw_DeviceDataService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_DeviceDataDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_DeviceDataService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_DeviceDataService>();
            }
        }
    
        public static IFlw_DeviceDataService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_DeviceDataService>(resolveNew: true);
            }
        }
    }
}
