//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_Good_BuybackService : BaseService<Flw_Good_Buyback>, IFlw_Good_BuybackService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_Good_BuybackService()
            : this(false)
        {
    
        }
    
        public Flw_Good_BuybackService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_Good_BuybackDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_Good_BuybackService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Good_BuybackService>();
            }
        }
    
        public static IFlw_Good_BuybackService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Good_BuybackService>(resolveNew: true);
            }
        }
    }
}
