//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_Game_FreeService : BaseService<Flw_Game_Free>, IFlw_Game_FreeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_Game_FreeService()
            : this(false)
        {
    
        }
    
        public Flw_Game_FreeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_Game_FreeDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_Game_FreeService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Game_FreeService>();
            }
        }
    
        public static IFlw_Game_FreeService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_Game_FreeService>(resolveNew: true);
            }
        }
    }
}
