//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_GroupVerityService : BaseService<Flw_GroupVerity>, IFlw_GroupVerityService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_GroupVerityService()
            : this(false)
        {
    
        }
    
        public Flw_GroupVerityService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_GroupVerityDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_GroupVerityService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_GroupVerityService>();
            }
        }
    
        public static IFlw_GroupVerityService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_GroupVerityService>(resolveNew: true);
            }
        }
    }
}
