//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_MemberInfo_ChangeService : BaseService<Flw_MemberInfo_Change>, IFlw_MemberInfo_ChangeService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_MemberInfo_ChangeService()
            : this(false)
        {
    
        }
    
        public Flw_MemberInfo_ChangeService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_MemberInfo_ChangeDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_MemberInfo_ChangeService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_MemberInfo_ChangeService>();
            }
        }
    
        public static IFlw_MemberInfo_ChangeService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_MemberInfo_ChangeService>(resolveNew: true);
            }
        }
    }
}
