//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Flw_CheckDateService : BaseService<Flw_CheckDate>, IFlw_CheckDateService
    {
    	public override void SetDal()
        {
    
        }
    
        public Flw_CheckDateService()
            : this(false)
        {
    
        }
    
        public Flw_CheckDateService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<IFlw_CheckDateDAL>(resolveNew: resolveNew);
        }
    
    	public static IFlw_CheckDateService I
        {
            get
            {
                return BLLContainer.Resolve<IFlw_CheckDateService>();
            }
        }
    
        public static IFlw_CheckDateService N
        {
            get
            {
                return BLLContainer.Resolve<IFlw_CheckDateService>(resolveNew: true);
            }
        }
    }
}
