//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Log_GameAlarmService : BaseService<Log_GameAlarm>, ILog_GameAlarmService
    {
    	public override void SetDal()
        {
    
        }
    
        public Log_GameAlarmService()
            : this(false)
        {
    
        }
    
        public Log_GameAlarmService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<ILog_GameAlarmDAL>(resolveNew: resolveNew);
        }
    
    	public static ILog_GameAlarmService I
        {
            get
            {
                return BLLContainer.Resolve<ILog_GameAlarmService>();
            }
        }
    
        public static ILog_GameAlarmService N
        {
            get
            {
                return BLLContainer.Resolve<ILog_GameAlarmService>(resolveNew: true);
            }
        }
    }
}
