//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudWebBar.BLL.XCCloud
{
    
    using XCCloudWebBar.DAL.Container;
    using XCCloudWebBar.DAL.IDAL.XCCloud;
    using XCCloudWebBar.BLL.Base;
    using XCCloudWebBar.BLL.Container;
    using XCCloudWebBar.BLL.IBLL.XCCloud;
    using XCCloudWebBar.Model.XCCloud;
    
    public partial class Search_TemplateService : BaseService<Search_Template>, ISearch_TemplateService
    {
    	public override void SetDal()
        {
    
        }
    
        public Search_TemplateService()
            : this(false)
        {
    
        }
    
        public Search_TemplateService(bool resolveNew)
        {
            Dal = DALContainer.Resolve<ISearch_TemplateDAL>(resolveNew: resolveNew);
        }
    
    	public static ISearch_TemplateService I
        {
            get
            {
                return BLLContainer.Resolve<ISearch_TemplateService>();
            }
        }
    
        public static ISearch_TemplateService N
        {
            get
            {
                return BLLContainer.Resolve<ISearch_TemplateService>(resolveNew: true);
            }
        }
    }
}
